export const ActionTypes = {
      SET_PRODUCTS: "SET_PRODUCTS",
      SELECTED_PRODUCT: "SELECTED_PRODUCT",
      REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
      SHOW_SPINNER: "SHOW_SPINNER",
      HIDE_SPINNER: "HIDE_SPINNER",
}